課題1 プログラム 
Lesson11_1.java
public class Lesson11_1 {
  public static void main(String[] args) {
    Calc.calc();
  }
}

Calc.java
import java.util.Scanner;
public class Calc {
  public static void calc() {
    // =============== ここに追加 ===================
    System.out.print("> ");
    Scanner scan = new Scanner(System.in);
    String input1Str = scan.next();
    String input2Str = scan.next();
    int input1 = Integer.parseInt(input1Str);
    int input2 = Integer.parseInt(input2Str);

    int result = input1 + input2;
    System.out.println(input1 + " + " + input2 + " = " + result);
    result = input1 - input2;
    System.out.println(input1 + " - " + input2 + " = " + result);
    result = input1 * input2;
    System.out.println(input1 + " * " + input2 + " = " + result);
    result = input1 / input2;
    System.out.println(input1 + " / " + input2 + " = " + result);

    // ============================================
  }
}

課題1　結果
G:\programing\java\Lesson11>java Lesson11_1
> 5 3
5 + 3 = 8
5 - 3 = 2
5 * 3 = 15
5 / 3 = 1


課題2
Lesson11_2.java
public class Lesson11_2 {
  public static void main(String[] args) {
    // ============ 処理の追加 ==============
    try{
      Calc.calc();
    } catch (NumberFormatException s){
      System.out.println("入力が int 型ではないため、エラーが発生しました");
    } catch (ArithmeticException e){
      System.out.println("ゼロで除算しようとしたため、エラーが発生しました");
    }
  }
}

Calc.java は課題1と同じです

課題2　結果
G:\programing\java\Lesson11>java Lesson11_2
> 1 1
1 + 1 = 2
1 - 1 = 0
1 * 1 = 1
1 / 1 = 1

G:\programing\java\Lesson11>java Lesson11_2
> 1 a
入力が int 型ではないため、エラーが発生しました

G:\programing\java\Lesson11>java Lesson11_2
> 5 0
5 + 0 = 5
5 - 0 = 5
5 * 0 = 0
ゼロで除算しようとしたため、エラーが発生しました


課題3　プログラム
Lesson11_3.java
public class Lesson11_3 {
  public static void main(String[] args) {
    // ============ 処理の追加 ==============
    int err = 0;
    for(int i = 1; i <= 3; i++){
      try{
        System.out.println("計算を開始します(" + i + "/3)");
        Calc.calc();
      } catch (NumberFormatException s){
        System.out.println("入力が int 型ではないため、エラーが発生しました");
        err++;
      } catch (ArithmeticException e){
        System.out.println("ゼロで除算しようとしたため、エラーが発生しました");
        err++;
      } 
    }
    int nor = 3 - err;
    System.out.println("正常に動作した回数: " + nor);
    System.out.println("例外が発生した回数: " + err);
  }
}

Calc.java は課題1と同じです

課題3　結果
G:\programing\java\Lesson11>java Lesson11_3
計算を開始します(1/3)
> 1 1
1 + 1 = 2
1 - 1 = 0
1 * 1 = 1
1 / 1 = 1
計算を開始します(2/3)
> a 2
入力が int 型ではないため、エラーが発生しました
計算を開始します(3/3)
> 1 0
1 + 0 = 1
1 - 0 = 1
1 * 0 = 0
ゼロで除算しようとしたため、エラーが発生しました
正常に動作した回数: 1
例外が発生した回数: 2


課題4　プログラム
Lesson11_4.java
public class Lesson11_4 {
  public static void main (String[] args) {
    String[] names = {"ヒロ", "ア", "ルイス・イ・ピカソ", "ヤマダ", "タロウ"};
    int[] ages = {18, 25, 20, 200, -1};
    User u = new User();

    for (int i = 0; i < names.length; i++) {
      try {
        u.setName(names[i]);
        u.setAge(ages[i]);
        System.out.println("名前:" + u.getName() + ", 年齢:" + u.getAge());
      } catch (NameOutOfBoundsException e) {
        System.out.println(e);
      } catch (AgeOutOfBoundsException e) {
        System.out.println(e);
      }
    }
  }
}

User.java
public class User {

  private String name;
  private int age;

  public User() {
    this.name = "名無し";
    this.age = 0;
  }
  // ============= ここに記述 ==============
  public void setName(String name) throws NameOutOfBoundsException{
    if(name.length() <= 1 || name.length() >= 8){
      throw new NameOutOfBoundsException("設定できない名前です:" + name);
    }else{
      this.name = name;
    }
  }
  public void setAge(int age) throws AgeOutOfBoundsException{
    if(age < 0 || age > 120){
      throw new AgeOutOfBoundsException("設定できない年齢です:" + age);
    }else{
      this.age = age;
    }
    
  }
  // =====================================

  public String getName() {
    return this.name;
  }

  public int getAge() {
    return this.age;
  }
}

AgeOutOfBoundsException.java
public class AgeOutOfBoundsException extends Exception{
    public AgeOutOfBoundsException(String msg){
        super(msg);
    }
}

NameOutOfBoundsException.java
public class NameOutOfBoundsException extends Exception{
    public NameOutOfBoundsException(String msg){
        super(msg);
    }
}

課題4　結果
G:\programing\java\Lesson11>java Lesson11_4
名前:ヒロ, 年齢:18
NameOutOfBoundsException: 設定できない名前です:ア
NameOutOfBoundsException: 設定できない名前です:ルイス・イ・ピカソ
AgeOutOfBoundsException: 設定できない年齢です:200
AgeOutOfBoundsException: 設定できない年齢です:-1


課題5　プログラム
Lesson11_5.java
public class Lesson11_5 {
  public static void main (String[] args) {
    java.util.Scanner scan = new java.util.Scanner(System.in);
    User u = new User();

    // ================ ここに記述 =================
    int age = 0;
    while(u.getName().equals("名無し") || u.getAge() == 0){
      try{
        System.out.print("ユーザーネーム: ");
        u.setName(scan.nextLine());

        System.out.print("年齢: "); 
        String ageStr = scan.nextLine();
        try{
          age = Integer.parseInt(ageStr);
        } catch (NumberFormatException e){
          System.out.println("年齢の入力が int 型ではないため、エラーが発生しました");
        }
        u.setAge(age);

      } catch (NameOutOfBoundsException e) {
        System.out.println(e);
      } catch (AgeOutOfBoundsException e) {
        System.out.println(e);
      }
    }
    System.out.println("名前:" + u.getName() + ", 年齢:" + u.getAge());
    // ===========================================
    
    scan.close();
  }
}

課題5　結果
G:\programing\java\Lesson11>java Lesson11_5
ユーザーネーム: ヒロ
年齢: a
年齢の入力が int 型ではないため、エラーが発生しました
ユーザーネーム: ア
NameOutOfBoundsException: 設定できない名前です:ア
ユーザーネーム: ヒロ
年齢: 200
AgeOutOfBoundsException: 設定できない年齢です:200
ユーザーネーム: ヒロ
年齢: 22
名前:ヒロ, 年齢:22